package com.example.calculator;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
 * Additional test cases generated by PR Coverage Analyzer
 * to improve test coverage for SimpleCalculator.
 * 
 * Generated on: 2025-09-13
 * Target coverage improvement: 20%
 */
public class SimpleCalculatorAdditionalTest {
    
    private SimpleCalculator calculator;
    
    @BeforeEach
    public void setUp() {
        calculator = new SimpleCalculator();
    }
    
    @Test
    public void testMultiply() {
        // Test basic multiplication
        assertEquals(6, calculator.multiply(2, 3));
        assertEquals(0, calculator.multiply(0, 5));
        assertEquals(-15, calculator.multiply(3, -5));
        
        // Test edge cases
        assertEquals(1, calculator.multiply(1, 1));
        assertEquals(0, calculator.multiply(0, 0));
    }
    
    @Test
    public void testDivide() {
        // Test basic division
        assertEquals(2, calculator.divide(6, 3));
        assertEquals(1, calculator.divide(5, 5));
        assertEquals(-3, calculator.divide(-9, 3));
    }
    
    @Test
    public void testDivideByZero() {
        // Test division by zero throws exception
        assertThrows(IllegalArgumentException.class, () -> {
            calculator.divide(5, 0);
        });
        
        assertThrows(IllegalArgumentException.class, () -> {
            calculator.divide(0, 0);
        });
    }
}
